### ISSUE TITLE
Error: Unsupported config option for services: 'verifier-api'

### ISSUE THREAD

**Issue by elvisMat** [walt-id/waltid-identity#105]
1. > `https://github.com/walt-id/waltid-identity.git`
2. > `cd docker-compose && docker-compose up`

Produces the following error: 
```sh
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'verifier-api'

```

I am on ubuntu

**Comment by ahmedsmiai** [comment]
Hello @elvisMat, I just tested it and it works fine, which docker compose version are you using ?

**Comment by elvisMat** [comment]
@ahmedsmiai  
![Screenshot_2024-02-01_18-51-27](https://github.com/walt-id/waltid-identity/assets/26812092/f4d8c0d3-0534-4a72-8910-3533760ff092)

**Comment by ahmedsmiai** [comment]
also what's you docker engine version, I would suggest that you upgrade both docker-compose and docker engine and see if it fixes the problem
