### ISSUE TITLE
SD-JWT VC spec

### ISSUE THREAD

**Issue by severinstampler** [walt-id/waltid-identity#19]
As I just looked through the verifiable-credential lib, I noticed the W3CVC class is issuing W3C credentials as SD-JWT with the **vc+sd-jwt** type, which is not entirely correct.

The **vc+sd-jwt** credential format is **NOT** the same as a W3C credential issued as SD-JWT, as pointed out in the [SD-JWT VC spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-sd-jwt-vc-01#name-sd-jwt-as-a-credential-form):

`... Note: This specification does not utilize the W3C's Verifiable Credentials Data Model v1.0, v1.1, or v2.0.`

**Comment by severinstampler** [comment]
yes

**Comment by alegomes** [comment]
What about now, @severinstampler ? May we close it?

**Comment by alegomes** [comment]
Closing after talking to @severinstampler
