### ISSUE TITLE
Create CHEQD DID (did:cheqd) feature not working

### ISSUE THREAD

**Issue by ChangoBuitrago** [walt-id/waltid-identity#288]
When you try to create a Cheqd DID from the Wallet (e.g. the hosted wallet `https://wallet.walt.id/`) you get the following error:

```
{exception: "true", status: "Bad Request", code: "400",…}
code
: 
"400"
exception
: 
"true"
message
: 
"Failed to finalize the did onboarding process.\nCheqd registrar returning \"The operation failed due to an internal error. Please try again: Error: Invalid base64 string format\""
status
: 
"Bad Request"
```

=> `Invalid base64 string format`

Thank you.

**Comment by SuperBatata** [comment]
Hi @ChangoBuitrago 

Thank you for reporting this issue. We have identified the cause of the problem.

We are pleased to inform you that this issue has been fixed. You should now be able to create a Cheqd DID from the Wallet  without encountering the error.

If you experience any further issues or have additional questions, please do not hesitate to reach out.
