### ISSUE TITLE
The endpoint `https://wallet.walt.id/exchange/issuance` could not be found in the current API.

### ISSUE THREAD

**Issue by ChangoBuitrago** [walt-id/waltid-identity#289]
Based on the documentation: 

"**authorizeBaseUrl** - is used to modify the start of the UR OID4VC request URL. If you are using the cross-device flow, where you will display the URL as a QR code, you can leave the value as openid4vp://authorize or if you don't know the wallet the user will be using to claim the credential. If you are using the same device flow, where you already know the user's wallet and want the user to be able to go directly to it, you can use the wallet URL path that is able to receive an OIDC request as a query parameter. Our wallet for example can receive OID4VC requests here https://wallet.walt.id/exchange/issuance."

Is the documentation outdated, or is the endpoint no longer supported? I appreciate this feature because it allows me to enhance interoperability with other wallets, which is a strong requirement for me.

Thank you for your help.

**Comment by SuperBatata** [comment]
@ChangoBuitrago  Thank you for bringing this issue to our attention. After reviewing the details, I found that my colleague has already addressed this issue. Therefore, I am closing it now. If you have any further questions or concerns, feel free to let us know.

Thank you for your understanding and support.
