### ISSUE TITLE
source code - location

### ISSUE THREAD

**Issue by marinkobabic** [walt-id/waltid-identity#39]
Please can you support here https://github.com/walt-id/waltid-web-wallet/issues/71 

Despite the announcement https://walt.id/blog/p/community-stack still not able to find the source code and your currently deployed version on the cloud is broken. SignUP does not work at all

`
Error
{"exception":"true","status":"Internal Server Error","code":"500","message":"org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: events)"}
`

**Comment by taminobaumann** [comment]
Hey @marinkobabic, 

sorry for the delayed reply. 

The links to the requested source-code: 

1. [Portal](https://github.com/walt-id/waltid-identity/tree/main/waltid-web-portal) 
2. [VC Repo](https://github.com/walt-id/waltid-credentials)

Hope this helps!

Best
Tamino
