### ISSUE TITLE
Error when I docker compose up Wallet Api 

### ISSUE THREAD

**Issue by InigoValdivielso** [walt-id/waltid-identity#395]
![image](https://github.com/walt-id/waltid-identity/assets/115789924/4cbf1b9e-d95c-4085-a902-35585c967443)

**Comment by mikeplotean** [comment]
it means `push.conf` file is missing or invalid
however, this file is not required for wallet-api to work (unless you need push-notifications)
so the wallet-api is functional even though some optional config files might be missing (such as push.conf)

**Comment by mikeplotean** [comment]
the new feature flag system that has been integrated [recently](https://github.com/walt-id/waltid-identity/pull/454) introduces optional feature functionality that avoids having these errors. Please check out the latest.
