### ISSUE TITLE
Device signature verification failing

### ISSUE THREAD

**Issue by hrvoje459** [walt-id/waltid-identity#420]
Hello,

I am trying to verify device signature on the separate device from which mdoc presentation was created,
I am getting some weird behaviour so I would appreciate any information or clarification on the topic:

this is the code I am trying to run:

    val my_credential = "cbor hex in attached file"

    val my_mdoc = MDoc.fromCBORHex(my_credential)

    println(my_credential.length)

    val dummy_request = MDocRequestBuilder("org.iso.18013.5.1.mDL")
        .addDataElementRequest("org.iso.18013.5.1", "portrait", false)
        .addDataElementRequest("org.iso.18013.5.1", "age_over_18", false)
        .build()

    val session_elements: List<AnyDataElement> = listOf(StringElement("some_value"), StringElement("some_value_2"))
    val sessionTranscript = ListElement(session_elements)

    val device_auth = DeviceAuthentication(
        sessionTranscript,
        "org.iso.18013.5.1.mDL",
        dummy_request.decodedItemsRequest.nameSpaces.toEncodedCBORElement()
    )

    println("Device auth: " + device_auth.toDE().toCBORHex())

    val device_jwk = JWKKey.generate(KeyType.secp256r1, JWKKeyMetadata())

    val device_key = ECKey.parse(device_jwk.exportJWK())

    val cryptoProvider_device = SimpleCOSECryptoProvider(
        listOf(
            //COSECryptoProviderKeyInfo("READER_KEY_ID", AlgorithmID.ECDSA_256, certChain.first().publicKey,  x5Chain = certChain, trustedRootCAs =  listOf(rootCaCertificate!!)),
            COSECryptoProviderKeyInfo("DEVICE_KEY_ID", AlgorithmID.ECDSA_256,  device_key!!.toECPublicKey(), device_key!!.toECPrivateKey(), x5Chain = listOf()),
        )
    )

    val presentation = my_mdoc
        .presentWithDeviceSignature(
            dummy_request,
            device_auth,
            cryptoProvider_device, "DEVICE_KEY_ID")

    println("Requested items: " + dummy_request.decodedItemsRequest.nameSpaces.toCBORHex())
    println("Presentation requested items: " + presentation.deviceSigned!!.nameSpaces.toCBORHex())

    // From this point we simulate verifier behaviour (separate device; can only infer requested items from the presentation)
    val device_auth_verifier_side = DeviceAuthentication(
        sessionTranscript,
        "org.iso.18013.5.1.mDL",
        presentation.deviceSigned!!.nameSpaces.toEncodedCBORElement(),
    )

    val presentation_chain = presentation.issuerSigned.issuerAuth!!.x5Chain!!
    val pres_chain = CertificateFactory.getInstance("X509").generateCertificates(
        ByteArrayInputStream(presentation_chain)
    ).map { it as X509Certificate }

    val cryptoProvider_reader = SimpleCOSECryptoProvider(listOf(
        //COSECryptoProviderKeyInfo("ISSUER_KEY_ID", AlgorithmID.ECDSA_256, pres_chain.first().publicKey, x5Chain =  pres_chain, trustedRootCAs =  listOf(pres_chain.last())),
        COSECryptoProviderKeyInfo("ISSUER_KEY_ID", AlgorithmID.ECDSA_256, pres_chain.first().publicKey, x5Chain =  pres_chain, trustedRootCAs =  listOf(pres_chain.last())),
        COSECryptoProviderKeyInfo("DEVICE_KEY_ID", AlgorithmID.ECDSA_256, device_key.toECPublicKey())

    ))

    val device_signature_verified = presentation.verifyDeviceSignature(device_auth_verifier_side, cryptoProvider_reader, "DEVICE_KEY_ID")

    println("Device signature valid: " + device_signature_verified.toString())

    val device_auth_with_dummy_request = DeviceAuthentication(
        sessionTranscript,
        "org.iso.18013.5.1.mDL",
        dummy_request.decodedItemsRequest.nameSpaces.toEncodedCBORElement()
    )

    val device_signature_verified_dummy = presentation.verifyDeviceSignature(device_auth_with_dummy_request, cryptoProvider_reader, "DEVICE_KEY_ID")

    println("Device signature valid: " + device_signature_verified_dummy.toString())

Resulting output:
`May 25, 2024 3:51:42 PM MDocPresentationIssueTestingKt main
INFO: Device auth: 847444657669636541757468656e7469636174696f6e826a736f6d655f76616c75656c736f6d655f76616c75655f32756f72672e69736f2e31383031332e352e312e6d444cd818582ba1716f72672e69736f2e31383031332e352e31a268706f727472616974f46b6167655f6f7665725f3138f4
May 25, 2024 3:51:42 PM MDocPresentationIssueTestingKt main
INFO: Requested items: a1716f72672e69736f2e31383031332e352e31a268706f727472616974f46b6167655f6f7665725f3138f4
May 25, 2024 3:51:42 PM MDocPresentationIssueTestingKt main
INFO: Presentation requested items: d81841a0
May 25, 2024 3:51:42 PM MDocPresentationIssueTestingKt main
INFO: Device signature valid: false
May 25, 2024 3:51:42 PM MDocPresentationIssueTestingKt main
INFO: Device signature valid: true`

Expected output: Device signature valid for both verification cases

This behaviour occurs because function [MDoc.presentWithDeviceSignature](https://github.com/walt-id/waltid-identity/blob/main/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/doc/MDoc.kt#L192) uses [empty map when creating DeviceSigned element](https://github.com/walt-id/waltid-identity/blob/main/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/doc/MDoc.kt#L197). Since mDL device can generate verifiable presentation of mDL with any subset of data elements, verifier can't know which subset to use to verify the presentation or would have to try to verify presentation with all possible subsets of data elements

In my local testing I replaced "mapOf()" with "mDocRequest.decodedItemsRequest.nameSpaces" which works fine for my use case.
Is this a bug or am I missing something?

[cbor_hex_credential.txt](https://github.com/walt-id/waltid-identity/files/15443823/cbor_hex_credential.txt)

**Comment by severinstampler** [comment]
Hi,
I found the problem in your code: 
In the `device_auth_verifier_side` you add the namespaces from the device-signed element. However, the device signed part doesn't contain the the document data, which was requested with the the MDocRequest. 
Instead, the device-signed object is like a proof of possession, where the device proves that it has ownership of the device key, which the document was issued for.

The requested document data, is in the issuer-signed object. As the data is e.g. personal data, that has been confirmed and signed by the document issuer.
When the device makes the presentation for the given MDocRequest, it may selectively choose the data to include in the presentation, so it filters the issuer-signed object according to the requested data items. (In your case "portrait" and "age_over_18")

Also with regards to your statement: "// From this point we simulate verifier behaviour (separate device; can only infer requested items from the presentation)"
I don' t quite agree with this assessment, as the document request was probably originally created by the verifier service and passed on to the device as a QR code or URL or likewise.
So you can assume, that the verifier knows which namespaces and data fields it requested from the device, such that it can assemble the device authentication structure correctly.

Anyway, the short summary is: The first verification fails, because the namespaces in the device authentication structure are taken from the device-signed object, which is a completely different type of object. You could take the fields from the issuer-signed object of the presentation instead, but I think the verifier should actually have the mdoc request, so that it can do it like in your second verification step, which succeeds in your case.

**Comment by hrvoje459** [comment]
Hi and thank you for your time,

with regards to your statement: "So you can assume, that the verifier knows which namespaces and data fields it requested from the device, such that it can assemble the device authentication structure correctly."

I agree partially, this would be the case if the device can only approve or decline request, but if the device decides to provide only a subset of requested data (selective disclosure), then the verifier would not know which data exactly it would need to assemble the device authentication structure.

I didn't think about extracting the fields from the issuer-signed object, thank you for the hint.

Additionally I would like to discuss this statement: "However, the device signed part doesn't contain the the document data, which was requested with the the MDocRequest.
Instead, the device-signed object is like a proof of possession, where the device proves that it has ownership of the device key, which the document was issued for."

If I am understanding you correctly, you are stating that device-signed object should not contain any information regarding nameSpaces and data items included in the presentation, this goes against my understanding of DeviceSigned structure so if you could clarify some things that would be awesome:

- what is the point of having [nameSpaces](https://github.com/walt-id/waltid-identity/blob/179d19cd1af052281da42e6267ede04b779fa06b/waltid-libraries/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/devicesigned/DeviceSigned.kt#L15) field in the structure if it will always be empty
- is this alligned with the current mDL standard, I only have access to one of the [draft versions](https://mobiledl-e5018.web.app/ISO_18013-5_E_draft.pdf) which defines DeviceSigned structure as such:

>
>
>
>
>
>

**Comment by hrvoje459** [comment]
@severinstampler after reading through specification again and with the help of your comment I was able to understand where I went wrong and what is DeviceNameSpaces used for.

Thank you for the help and clarification.

**Comment by hrvoje459** [comment]
Resolved
