### ISSUE TITLE
maven repo is missing latest release artifacts

### ISSUE THREAD

**Issue by sake** [walt-id/waltid-identity#447]
According to the docs in this repo (https://github.com/walt-id/waltid-identity/tree/main/waltid-verifiable-credentials), the release artifacts should be found in the maven repo `https://maven.waltid.dev/releases`. 
In this repo, there are only parts of the 0.3.0 release. 

In the other documentation (https://docs.oss.walt.id/issuer/sdks/setup/open-source), which is also referenced from the top level README, no newer artifacts are published.

The documentation should be aligned and the artifacts should be available there.

**Comment by ayoubagrebi** [comment]
Appreciate your understanding! The documentation has been updated to reflect the availability of the latest artifacts. 
https://docs.oss.walt.id/issuer/sdks/setup/open-source .You can use release 0.3.1 instead of 0.3.0.

**Comment by sake** [comment]
Perfect, thank you! My raised issues are all addressed, so I'm closing it.
