### ISSUE TITLE
Issuer Metadata Problem wrt OID4VCI Draft13 

### ISSUE THREAD

**Issue by vanhoanHoang** [walt-id/waltid-identity#463]
I have pulled all tested the v0.3 release and identify that we might have a problem related to metadata defined in the OID4VCI Draft 13. 

In the Draft 13, for each element in credential_configurations_supported, there must be a credential_definition object which contains type and multiple optional properties.

However, by looking at the metadata in the Issuer API, I see that there are not credential_definition object in each supported credential configuration. More specifically, below is what exposed by Issuer API
```json 
{
    "BankId_jwt_vc_json": {
      "id": "BankId_jwt_vc_json",
      "format": "jwt_vc_json",
      "cryptographic_binding_methods_supported": [
        "did"
      ],
      "cryptographic_suites_supported": [
        "EdDSA",
        "ES256",
        "ES256K",
        "RSA"
      ],
      "types": [
        "VerifiableCredential",
        "BankId"
      ]
}
```

while the following should be exposed instead: 

```json
{
   "BankId_jwt_vc_json":{
      "id":"BankId_jwt_vc_json",
      "format":"jwt_vc_json",
      "cryptographic_binding_methods_supported":[
         "did"
      ],
      "cryptographic_suites_supported":[
         "EdDSA",
         "ES256",
         "ES256K",
         "RSA"
      ],
      "credential_definition":{
         "types":[
            "VerifiableCredential",
            "BankId"
         ]
      }
   }
}
```

Can you have a look at it ? 

Cheer, 
Hoan

**Comment by alegomes** [comment]
Thanks so much for your report, Hoan. It's a very nice contribution. We'll tackle it as soon as possible.
