### ISSUE TITLE
TSE-key integration not working for default DIDs

### ISSUE THREAD

**Issue by niwim** [walt-id/waltid-identity#480]
When a default did is generated (without a specific key being provided) the application will always generate a local key even if the application is configured to use TSE (or any other integration) as default.

The issue is related to the [WalletService](https://github.com/walt-id/waltid-identity/blob/a47dbdfc1144f2f85e42e2e25350457482ff8da4/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt#L345) implementation that only use the default setup (note not the default config). So the key will always be the [hard-coded](https://github.com/walt-id/waltid-identity/blob/a47dbdfc1144f2f85e42e2e25350457482ff8da4/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletService.kt#L52) default - JWK as can be seen [here](https://github.com/walt-id/waltid-identity/blob/a47dbdfc1144f2f85e42e2e25350457482ff8da4/waltid-crypto/src/commonMain/kotlin/id/walt/crypto/keys/KeyGenerationRequest.kt#L7).

I have a suggested fix that can be seen [here](https://github.com/niwim/waltid-identity/pull/1), note that to run this the TSE-config needs to be setup.

I haven't opened a PR for this issue as the fix builds on my other [fix](https://github.com/walt-id/waltid-identity/pull/476) [as seen in issue](https://github.com/walt-id/waltid-identity/issues/475).

**Comment by SuperBatata** [comment]
@waltkb

**Comment by niwim** [comment]
Hi @waltkb,

I've tested and I'm getting the integration to work as per issue #475 so that is solved. However, the default configuration is not working as I expect. My understanding of the intention is possibly wrong, when I generate a new DID without providing a specific key (expecting the default config to be used) the key generation is using the local provider rather than the Vault.

This deviates between the [AccountService](https://github.com/walt-id/waltid-identity/blob/b65bfd29df6c6d4c2f6765204702c6d69441f45e/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/account/AccountsService.kt#L56) and the [WalletService](https://github.com/walt-id/waltid-identity/blob/b65bfd29df6c6d4c2f6765204702c6d69441f45e/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt#L317). Not by intention, as I read it, but in effect.

Like you state the key is generated correctly and the right key is coupled with the right DID. However, the DID generated at account creation will use the TSE-provider but any DID generated without an explicit key will use the local provider.

This is my configuration:

```
defaultDidConfig: {
    method: jwk
}
 defaultKeyConfig: {
     backend: tse
     config: {
         server: "http://127.0.0.1:8200/v1/transit"
         accessKey: "<token>"
     }
     keyType: Ed25519
 }
```

If I create a new user the following key (including corresponding DID) is generated via the AccountService:

```
[
  {
    "algorithm": "Ed25519",
    "cryptoProvider": "[TSE Ed25519 key @ http://127.0.0.1:8200/v1/transit]",
    "keyId": {
      "id": "-TIB4znkiFcyYJQ3nejBJOsJuxJn-YMeMyRO6MEZ0eI"
    },
    "keyPair": {},
    "keysetHandle": null
  },
]
```

However, if I create a new did via the dids/create/jwk endpoint for the same user (and providing no key) the key is not generated in the Vault but locally:

```
[
  {
    "algorithm": "Ed25519",
    "cryptoProvider": "[TSE Ed25519 key @ http://127.0.0.1:8200/v1/transit]",  <--
    "keyId": {
      "id": "-TIB4znkiFcyYJQ3nejBJOsJuxJn-YMeMyRO6MEZ0eI"
    },
    "keyPair": {},
    "keysetHandle": null
  },
  {
    "algorithm": "Ed25519",
    "cryptoProvider": "[walt.id CoreCrypto private Ed25519 key]",  <--
    "keyId": {
      "id": "DITbyNV0rbQEvV6YbHhfKM7NahX4av0Sr-1J00K4YrM"
    },
    "keyPair": {},
    "keysetHandle": null
  }
]
```

My expectation is that any DID generated without explicit instruction should use the defalt-config, but my understanding of this might be incorrect?

**Comment by niwim** [comment]
> Hi @waltkb @taminobaumann,
> 
> I'm sorry to be a bit of a bother. I'm not sure this issue is completely fixed. I haven't fully understood the feature flags yet so I might be jumping the gun a bit, but when I test the latest version I'm still failing to use the default config.
> 
> As I understand it [this is the part](https://github.com/walt-id/waltid-identity/blob/11cb4eda091cb9d59ba99548197e024a11ddcfbb/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt#L415) that should add the default-config if no KeyGenerationRequest is provided. However, KeyGenerationRequest has a hardcoded default value so it will never be null as can be seen in [WalletService](https://github.com/walt-id/waltid-identity/blob/11cb4eda091cb9d59ba99548197e024a11ddcfbb/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletService.kt#L52) and in [KeyGenerationRequest](https://github.com/walt-id/waltid-identity/blob/11cb4eda091cb9d59ba99548197e024a11ddcfbb/waltid-libraries/waltid-crypto/src/commonMain/kotlin/id/walt/crypto/keys/KeyGenerationRequest.kt#L7).

I belive this is the source of the issue.
