### ISSUE TITLE
Failure in Credentials Verification

### ISSUE THREAD

**Issue by mahtovivekUBT** [walt-id/waltid-identity#481]
I took the checkout of the latest walt.id repo and built the images locally and ran the setup with local built images.
But whenever I try verifying the credentials, it fails

This is the last log I see in the wallet-api docker (Attached log.txt)

Is there an issue with the presentation?

![Screenshot 2024-06-10 155423](https://github.com/walt-id/waltid-identity/assets/101926823/94786afc-f23b-4994-83e3-6f1a8d48a7ab)
[log.txt](https://github.com/user-attachments/files/15774516/log.txt)

**Comment by niwim** [comment]
I'm seeing a similar issue but on the offer side, seems to be related to [this PR](https://github.com/walt-id/waltid-identity/pull/473). 

The browser isn't reaching the the issuer-container as the host of the vc-request sting is a internal docker URL reference.

<img width="1325" alt="Screenshot 2024-06-11 at 09 42 09" src="https://github.com/walt-id/waltid-identity/assets/10028990/444b3729-acab-42c3-903c-2e58f446114e">

**Comment by SuperBatata** [comment]
@niwim in the `etc/hosts` file you can add those lines to resolve the issue : 

127.0.0.1 host.docker.internal
127.0.0.1 gateway.docker.internal

**Comment by niwim** [comment]
Thanks @SuperBatata, noticed that the issues were not related.

Managed to reproduce @mahtovivekUBT issue. It looks like its ebsi-related, idk much about the ebsi resolver but managed to extract this error at least.

```
docker-compose-verifier-api-1       | [DefaultDispatcher-worker-8] TRACE id.walt.credentials.schemes.JwsSignatureScheme - Verifying with issuer did: did:ebsi:zf39qHTXaLrr6iy3tQhT3UZ
docker-compose-verifier-api-1       | [DefaultDispatcher-worker-8] TRACE id.walt.credentials.schemes.JwsSignatureScheme - Imported key: Failure(io.ktor.network.tls.TLSException: Received alert during handshake. Level: FATAL, code: ProtocolVersion) from did: did:ebsi:zf39qHTXaLrr6iy3tQhT3UZ, public is: null
```

**Comment by laserguy** [comment]
Thanks @SuperBatata  and @niwim 

These are the logs from the verifier_api (After clicking on accept presentation)
[verifier_api.log](https://github.com/user-attachments/files/15791975/verifier_api.log)

I have Windows 11 OS with Docker-desktop, and I'm running the demo on Chrome browser although the behavior is same on other browsers. Please let me know if you need any more info.

**Comment by SuperBatata** [comment]
@laserguy Thank you for providing the logs from the verifier-api. Could you please also provide the steps to reproduce the issue? For example, how are you running the project, and how do you issue the VC? etc..  This information will help us better understand and address the problem. Thank you!

**Comment by laserguy** [comment]
@SuperBatata I tried with `did:jwk`, and the verification works with it. I tried with other _did_ methods as well.
Except `did:key` and `did:cheqd`, other methods are working fine.

I have made a video that shows how issue can be reproduced, but it is more than 10 MB so I have uploaded it to the discord [Failed Verification](https://discord.com/channels/950664482877763656/1249726530234482818)

**Comment by laserguy** [comment]
@SuperBatata I had one small question, I was able to resolve the `did:cheqd` using _Uniresolver_, but I couldn't resolve the `did:ebsi`. Is `did:ebsi` not stored on the `ebsi` blockchain?

`did:ebsi:zf39qHTXaLrr6iy3tQhT3UZ`
