### ISSUE TITLE
[wallet-api] Inconsistent error codes when using the wrong wallet-id to access api

### ISSUE THREAD

**Issue by mikeplotean** [walt-id/waltid-identity#509]
### Description

When trying to reproduce horizontal privilege escalation and use a wallet-id which is not assigned to currently logged in account, for different endpoints there are different error codes and response types.

**Environment**
- dev - https://wallet.walt-test.cloud
- local - docker-compose

Steps to reproduce
1. register account
2. log into wallet
3. copy wallet-id
4. register another account
5. log into wallet
6. use the wallet-id from step#3 when accessing authorized api (e.g. list dids, keys, events, generate key, did, etc)

### Expected

- error code 400 is received
- error message says "This account does not have access to the specified wallet."

### Actual

- for some apis, e.g. list events, generate key
  - error code 400 is displayed 
  - error message "This account does not have access to the specified wallet."
- for other apis, e.g. list dids, create did:jwk
  - error code 500 is displayed 
  - error message
```
{
    "exception": true,
    "status": "Internal Server Error",
    "code": "500",
    "message": "This account does not have access to the specified wallet."
}
```

**Comment by SuperBatata** [comment]
should be fixed with this pr : #597
