### ISSUE TITLE
500 internal server error on missing resource/denied access

### ISSUE THREAD

**Issue by pohutukawa** [walt-id/waltid-identity#582]
**Describe the bug**
When calling operations on the `wallet-api`, I am receiving a `500 internal server error` as opposed to a `404 Not Found` error as expected, if a user attempts to access a wallet not theirs or not existent. The API responds in a non-graceful way not best practice for RESTful APIs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain an access token of a registered user (in this case stored in the `TOKEN` environment variable)
2. Request the DIDs of a wallet non-exsistent:

```
curl -X 'GET' \
  'http://localhost:7001/wallet-api/wallet/ffffffff-45f6-4e77-9f4f-70b6f6dcc018/dids' \
  -H 'accept: application/json' \
  -H "Authorization: Bearer $TOKEN"
```
3. Receive a 500 error response:
```
{"exception":true,"status":"Internal Server Error","code":"500","message":"This account does not have access to the specified wallet."}
```

**Expected behaviour**
To not allow for any data probing/harvesting, an API should return a `404` error on resources not accessible by them, rather than a `403 Forbidden`.

**Actual behaviour**
A `500 Internal Server Error` is returned, resulting from an unhandled server exception (`id.walt.webwallet.web.ForbiddenException`)

**Environment**
**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Browser: Command line (`curl`), but the same for Swagger UI

**Comment by cpatsonakis** [comment]
Hi!

Thank you for submitting this bug report and bringing this issue to our attention.

We will discuss internally including a fix as part of our development cycles.
