### ISSUE TITLE
Can't use the default onboarding did to claim credentials

### ISSUE THREAD

**Issue by mikeplotean** [walt-id/waltid-identity#625]
**Describe the bug**
When attempting to claim credential using the default did, it fails. Also, the wallet's keys page shows no default key.

**To Reproduce**
1. Go to [portal](https://portal.walt-test.cloud)
2. Issue any credential
3. Copy credential-offer-url
4. Go to [web-wallet](https://wallet.walt-test.cloud)
5. Click on 'Scan to present or receive credential'
6. Paste the credential-offer-url (form step#3)
7. Click 'Receive credential'
8. Click 'Accept'

**Expected behavior**
Credential is claimed successfully.

**Actual behavior**
- credential is not claimed
- a popup showing an error is displayed (see screenshots)

**Screenshots**
![image](https://github.com/user-attachments/assets/6addc0c5-a399-4127-b7fd-7008fbc72f33)

**Environment**
- https://wallet.walt-test.cloud

**Additional context**
The account must be created before Jul.12th.

**Comment by dinkar-jain** [comment]
Reference https://github.com/walt-id/waltid-identity/pull/624
