### ISSUE TITLE
Docker macos arm64

### ISSUE THREAD

**Issue by waltkb** [walt-id/waltid-identity#628]
Docker containers should be runnable when the host is macOS and the host system uses a ARM64 processor (e.g. M1/M2/M3).

Build is not possible, due to `Native compilation is not yet supported for aarch64 on Windows / Linux` (the containers are Linux based, but it's run from ARM64)

**Comment by matteo-ms** [comment]
you have to build using docker buildx build --platform linux/amd64,linux/arm64/v8
