### ISSUE TITLE
Kotlin internal error exposed by the API

### ISSUE THREAD

**Issue by alegomes** [walt-id/waltid-identity#68]
When a login request is issued to the Wallet API without correctly filling in the required parameters, the API returns an internal Kotlin error. 

![image](https://github.com/walt-id/waltid-identity/assets/34938/3b3f8315-1e88-4946-bdf2-79e3d71d747c)

For the sake of API semantics, wouldn't it be better if we encapsulated this internal language error in an error more related to the authentication process?

[]s

**Comment by SuperBatata** [comment]
should be fixed with this pr : #597
