### ISSUE TITLE
Wallet Presentation Issues in Release 0.6

### ISSUE THREAD

**Issue by vanhoanHoang** [walt-id/waltid-identity#692]
Hi team, 

I have pulled the latest release of the waltid identity to test it out. The release has been improved significantly overrall. 
There are however some problems with the wallets especially related to the presentation protocol when Wallet submits an sd-jwt-vc. More specifically, I try to test with a Sd-jwt credential issued by the Portal and try to authenticate with it. Here is an error returned: 

`  Verifier API : Error: Verification failed: String does not have JWS part amount of 3 (= 2 dots): eyJraWQiOiJkaWQ6andrOmV5SnJkSGtpT2lKRlF5SXNJbU55ZGlJNklsQXRNalUySWl3aWEybGtJam9pTTFsT1pEbEdibmc1U214NVVGWlpkMmRYUmtVek4wVXpSM2RKTUdWSGJFTkxPSGRHYkZkNFIyWndUU0lzSW5naU9pSkdiM1paTWpGTVFVRlBWR3huTFcwdFRtVkxWMmhhUlV3MVlVWnlibEl3ZFdOS2FrUTFWRXR3UjNWbklpd2llU0k2SWtOeVJrcG1SMVJrVURJNVNrcGpZM0JSV0hWNVRVOHpiMmgwZW5KVWNWQjZRbEJDU1ZSWmFqQnZaMEVpZlEiLCJjdHkiOiJjcmVkZW50aWFsLWNsYWltcy1zZXQranNvbiIsInR5cCI6InZjK3NkLWp3dCIsImFsZyI6IkVTMjU2In0.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiQmFua0lkIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7Il9zZCI6WyIweFRLNTJyYzU3RVdzbDFwSkJHUFZtSk9TLU5EUkZBU2dDTkxaZWVQYVdNIiwiT0JrSzd5bmhBZV9pczJ5Y09HZ3gwcGFrOHFsa1c2bkFOZm1SUDY0cjl2WSIsIkJBczhrZWlEQXhWRGZyVVk4MGxTcGZTSGNEbFd4MDBIYkFzRVdzelF6S0UiLCI5cTk2N1F2ZUtvTjhkWjFRX3ZEaXBXTG5HYnBzdVpKUFZKMWYzdmNfRkg0IiwiOFpmdVJzV2U3N2xrbFVEcmhYaXhsT1pUUjZheTlnMEVwLVhLaHI3V2syWSIsIlF6LWRETFhaV3RCN1NmOHBWdC1GdVhhVXVmRWVqOEdHUUlpajRQajJVNTQiLCIySDRRSmZlSHNWakNSbHNrYUhmQ0VZclc4SjQyTkYwS21UQUlEZVRaa1cwIl19LCJpZCI6InVybjp1dWlkOjY3NzZjMDMyLWE1NDgtNDM0Mi1hNzdhLWJjNzkyMjk4YTA5ZiIsImlzc3VlZCI6IjIwMjEtMDgtMzFUMDA6MDA6MDBaIiwiaXNzdWVyIjp7ImlkIjoiZGlkOmp3azpleUpyZEhraU9pSkZReUlzSW1OeWRpSTZJbEF0TWpVMklpd2lhMmxrSWpvaU0xbE9aRGxHYm5nNVNteDVVRlpaZDJkWFJrVXpOMFV6UjNkSk1HVkhiRU5MT0hkR2JGZDRSMlp3VFNJc0luZ2lPaUpHYjNaWk1qRk1RVUZQVkd4bkxXMHRUbVZMVjJoYVJVdzFZVVp5YmxJd2RXTktha1ExVkV0d1IzVm5JaXdpZVNJNklrTnlSa3BtUjFSa1VESTVTa3BqWTNCUldIVjVUVTh6YjJoMGVuSlVjVkI2UWxCQ1NWUlphakJ2WjBFaWZRIiwiaW1hZ2UiOnsiaWQiOiJodHRwczovL2ltYWdlcy5zcXVhcmVzcGFjZS1jZG4uY29tL2NvbnRlbnQvdjEvNjA5YzBkZGY5NGJjYzAyNzhhN2NiZGI0LzE2NjAyOTYxNjkzMTMtSzE1OUs5V1g4SjhQUEpFMDA1SFYvV2FsdCtCb3RfTG9nby5wbmc_Zm9ybWF0PTEwMHciLCJ0eXBlIjoiSW1hZ2UifSwibmFtZSI6IkNIIEF1dGhvcml0eSIsInR5cGUiOiJQcm9maWxlIiwidXJsIjoiaHR0cHM6Ly9pbWFnZXMuc3F1YXJlc3BhY2UtY2RuLmNvbS9jb250ZW50L3YxLzYwOWMwZGRmOTRiY2MwMjc4YTdjYmRiNC8xNjYwMjk2MTY5MzEzLUsxNTlLOVdYOEo4UFBKRTAwNUhWL1dhbHQrQm90X0xvZ28ucG5nP2Zvcm1hdD0xMDB3In0sInZhbGlkRnJvbSI6IjIwMjEtMDgtMzFUMDA6MDA6MDBaIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wOC0xM1QxMzowMTowNS43NDE5MjI4MzRaIiwiaXNzIjoiZGlkOmp3azpleUpyZEhraU9pSkZReUlzSW1OeWRpSTZJbEF0TWpVMklpd2lhMmxrSWpvaU0xbE9aRGxHYm5nNVNteDVVRlpaZDJkWFJrVXpOMFV6UjNkSk1HVkhiRU5MT0hkR2JGZDRSMlp3VFNJc0luZ2lPaUpHYjNaWk1qRk1RVUZQVkd4bkxXMHRUbVZMVjJoYVJVdzFZVVp5YmxJd2RXTktha1ExVkV0d1IzVm5JaXdpZVNJNklrTnlSa3BtUjFSa1VESTVTa3BqWTNCUldIVjVUVTh6YjJoMGVuSlVjVkI2UWxCQ1NWUlphakJ2WjBFaWZRIiwiY25mIjp7ImtpZCI6ImRpZDpqd2s6ZXlKcmRIa2lPaUpQUzFBaUxDSmpjbllpT2lKRlpESTFOVEU1SWl3aWEybGtJam9pU1c4dFRIbFBOVVl6WkZKM2FUVlBUbTVaVWpNMGJtUllRa2hJYTBWT1ZIZDRaQzE0U3pGM05WQjJSU0lzSW5naU9pSnBjRGRaTFZGM2VIbEhjSEEyYTBWYWVYcDZabE5ZZFROVVozRldZVUozYVRKMFNDMWFhRXRVVEZoUkluMCJ9LCJ2Y3QiOiJCYW5rSWRfdmMrc2Qtand0IiwianRpIjoidXJuOnV1aWQ6Njc3NmMwMzItYTU0OC00MzQyLWE3N2EtYmM3OTIyOThhMDlmIiwiaWF0IjoxNzIzNTU0MDY1LCJuYmYiOjE3MjM1NTQwNjV9.ewojjDkUYGXuNClczUAY2ySZH6Q0cffNKK5Qy9_dkzXNteffTGkMDh9o_GXXqeaYkS8ZFknNH8TA9meyKaM4ag~eyJraWQiOiJJby1MeU81RjNkUndpNU9ObllSMzRuZFhCSEhrRU5Ud3hkLXhLMXc1UHZFIiwidHlwIjoia2Irand0IiwiYWxnIjoiRWREU0EifQ.eyJpYXQiOjE3MjM1NjUzNzMsImF1ZCI6Imh0dHA6Ly9ob3N0LmRvY2tlci5pbnRlcm5hbDo3MDAzL29wZW5pZDR2Yy92ZXJpZnkiLCJub25jZSI6ImQyMTFlZGRjLTE2YjAtNGY1Yy1hZDZhLWU1ZjMzYzZjMjVkZCIsInNkX2hhc2giOiJzOEt1YzNWVldha2RlaWQ5WWJQMHF3RnduRld2NTFMS3g3THlmeXdjeTdFIn0.x_2dIW03plZzN3ND5OUwVXKg2JxD0Vro8_gOSe5PdWM-7dnUly4a19WR7a1j2fJ2AA4Wo3kBYl71rr-I-pDSBQ
`  

Actually there are no disclosures sent by the Wallet to Verifier. And The Verifier could not verify the signature because the wallet concatenates another jwt for key binding. and the Verifier takes both Jwts as one single input to verify. 

Could you please have a look ? 

Cheers, 
Hoan

**Comment by alegomes** [comment]
Sure! Let's check it out.

**Comment by alegomes** [comment]
Hi @vanhoanHoang .

We are working on it at #701 and it will be merged soon.

**Comment by vanhoanHoang** [comment]
Thank you @alegomes  for your response 

However I spot another problem with both sd_jwt_vc and mso_mdoc. 
Currently, for authorization response sent to Verifier,  Wallet is only wrapping  jwt_vc_json credential into the vp_token.

For sd_jwt_vc and mso_mdoc, they are sent directly to Verifier as you can see [here](https://github.com/walt-id/waltid-identity/blob/main/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt#L248)

I'm not sure if this was intentional or a mistake. I look up the OID4VP spec again but apparently nothing has been changed with regards to the Authorization Response. And for any format, Wallet should wrap credentials into vp_token. 

Thank you for your help :)

Cheer, 
Hoan

**Comment by vanhoanHoang** [comment]
Thank you @alegomes for your help. 

As indicated in the example above, there was no disclosures sent by Wallet to Verifier even though I chose to reveal them on the Wallet UI. 

I looked at the code [here](https://github.com/walt-id/waltid-identity/blob/main/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt#L202), apparently it is not added if I'm not wrong ?

Cheers
Hoan

**Comment by alegomes** [comment]
Hey, @vanhoanHoang 

If it's related to another problem, just to keep things organized and easier to track, do you mind opening new issues for them? ;-)

All the best,
Ale

**Comment by vanhoanHoang** [comment]
Dear @alegomes,

I'm creating a new issue :) 
Thank you
