### ISSUE TITLE
Missing revealed disclosures during a sd-jwt-vc authentication session 

### ISSUE THREAD

**Issue by vanhoanHoang** [walt-id/waltid-identity#713]
Dear team,

As discussed at the end of another issue [#692](https://github.com/walt-id/waltid-identity/issues/692), during an SD JWT VC authentication session, the Wallet does not send disclosures chosen by User on the Wallet UI. Look like the code here show it in todo if I understand correctly: [code](https://github.com/walt-id/waltid-identity/blob/main/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt#L202)

Here is an example of an authorization response which does not contain disclosures chosen by User on Wallet, but only sd-jwt and kb-jwt. 

` Verifier API : Error: Verification failed: String does not have JWS part amount of 3 (= 2 dots): eyJraWQiOiJkaWQ6andrOmV5SnJkSGtpT2lKRlF5SXNJbU55ZGlJNklsQXRNalUySWl3aWEybGtJam9pTTFsT1pEbEdibmc1U214NVVGWlpkMmRYUmtVek4wVXpSM2RKTUdWSGJFTkxPSGRHYkZkNFIyWndUU0lzSW5naU9pSkdiM1paTWpGTVFVRlBWR3huTFcwdFRtVkxWMmhhUlV3MVlVWnlibEl3ZFdOS2FrUTFWRXR3UjNWbklpd2llU0k2SWtOeVJrcG1SMVJrVURJNVNrcGpZM0JSV0hWNVRVOHpiMmgwZW5KVWNWQjZRbEJDU1ZSWmFqQnZaMEVpZlEiLCJjdHkiOiJjcmVkZW50aWFsLWNsYWltcy1zZXQranNvbiIsInR5cCI6InZjK3NkLWp3dCIsImFsZyI6IkVTMjU2In0.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiQmFua0lkIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7Il9zZCI6WyIweFRLNTJyYzU3RVdzbDFwSkJHUFZtSk9TLU5EUkZBU2dDTkxaZWVQYVdNIiwiT0JrSzd5bmhBZV9pczJ5Y09HZ3gwcGFrOHFsa1c2bkFOZm1SUDY0cjl2WSIsIkJBczhrZWlEQXhWRGZyVVk4MGxTcGZTSGNEbFd4MDBIYkFzRVdzelF6S0UiLCI5cTk2N1F2ZUtvTjhkWjFRX3ZEaXBXTG5HYnBzdVpKUFZKMWYzdmNfRkg0IiwiOFpmdVJzV2U3N2xrbFVEcmhYaXhsT1pUUjZheTlnMEVwLVhLaHI3V2syWSIsIlF6LWRETFhaV3RCN1NmOHBWdC1GdVhhVXVmRWVqOEdHUUlpajRQajJVNTQiLCIySDRRSmZlSHNWakNSbHNrYUhmQ0VZclc4SjQyTkYwS21UQUlEZVRaa1cwIl19LCJpZCI6InVybjp1dWlkOjY3NzZjMDMyLWE1NDgtNDM0Mi1hNzdhLWJjNzkyMjk4YTA5ZiIsImlzc3VlZCI6IjIwMjEtMDgtMzFUMDA6MDA6MDBaIiwiaXNzdWVyIjp7ImlkIjoiZGlkOmp3azpleUpyZEhraU9pSkZReUlzSW1OeWRpSTZJbEF0TWpVMklpd2lhMmxrSWpvaU0xbE9aRGxHYm5nNVNteDVVRlpaZDJkWFJrVXpOMFV6UjNkSk1HVkhiRU5MT0hkR2JGZDRSMlp3VFNJc0luZ2lPaUpHYjNaWk1qRk1RVUZQVkd4bkxXMHRUbVZMVjJoYVJVdzFZVVp5YmxJd2RXTktha1ExVkV0d1IzVm5JaXdpZVNJNklrTnlSa3BtUjFSa1VESTVTa3BqWTNCUldIVjVUVTh6YjJoMGVuSlVjVkI2UWxCQ1NWUlphakJ2WjBFaWZRIiwiaW1hZ2UiOnsiaWQiOiJodHRwczovL2ltYWdlcy5zcXVhcmVzcGFjZS1jZG4uY29tL2NvbnRlbnQvdjEvNjA5YzBkZGY5NGJjYzAyNzhhN2NiZGI0LzE2NjAyOTYxNjkzMTMtSzE1OUs5V1g4SjhQUEpFMDA1SFYvV2FsdCtCb3RfTG9nby5wbmc_Zm9ybWF0PTEwMHciLCJ0eXBlIjoiSW1hZ2UifSwibmFtZSI6IkNIIEF1dGhvcml0eSIsInR5cGUiOiJQcm9maWxlIiwidXJsIjoiaHR0cHM6Ly9pbWFnZXMuc3F1YXJlc3BhY2UtY2RuLmNvbS9jb250ZW50L3YxLzYwOWMwZGRmOTRiY2MwMjc4YTdjYmRiNC8xNjYwMjk2MTY5MzEzLUsxNTlLOVdYOEo4UFBKRTAwNUhWL1dhbHQrQm90X0xvZ28ucG5nP2Zvcm1hdD0xMDB3In0sInZhbGlkRnJvbSI6IjIwMjEtMDgtMzFUMDA6MDA6MDBaIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wOC0xM1QxMzowMTowNS43NDE5MjI4MzRaIiwiaXNzIjoiZGlkOmp3azpleUpyZEhraU9pSkZReUlzSW1OeWRpSTZJbEF0TWpVMklpd2lhMmxrSWpvaU0xbE9aRGxHYm5nNVNteDVVRlpaZDJkWFJrVXpOMFV6UjNkSk1HVkhiRU5MT0hkR2JGZDRSMlp3VFNJc0luZ2lPaUpHYjNaWk1qRk1RVUZQVkd4bkxXMHRUbVZMVjJoYVJVdzFZVVp5YmxJd2RXTktha1ExVkV0d1IzVm5JaXdpZVNJNklrTnlSa3BtUjFSa1VESTVTa3BqWTNCUldIVjVUVTh6YjJoMGVuSlVjVkI2UWxCQ1NWUlphakJ2WjBFaWZRIiwiY25mIjp7ImtpZCI6ImRpZDpqd2s6ZXlKcmRIa2lPaUpQUzFBaUxDSmpjbllpT2lKRlpESTFOVEU1SWl3aWEybGtJam9pU1c4dFRIbFBOVVl6WkZKM2FUVlBUbTVaVWpNMGJtUllRa2hJYTBWT1ZIZDRaQzE0U3pGM05WQjJSU0lzSW5naU9pSnBjRGRaTFZGM2VIbEhjSEEyYTBWYWVYcDZabE5ZZFROVVozRldZVUozYVRKMFNDMWFhRXRVVEZoUkluMCJ9LCJ2Y3QiOiJCYW5rSWRfdmMrc2Qtand0IiwianRpIjoidXJuOnV1aWQ6Njc3NmMwMzItYTU0OC00MzQyLWE3N2EtYmM3OTIyOThhMDlmIiwiaWF0IjoxNzIzNTU0MDY1LCJuYmYiOjE3MjM1NTQwNjV9.ewojjDkUYGXuNClczUAY2ySZH6Q0cffNKK5Qy9_dkzXNteffTGkMDh9o_GXXqeaYkS8ZFknNH8TA9meyKaM4ag~eyJraWQiOiJJby1MeU81RjNkUndpNU9ObllSMzRuZFhCSEhrRU5Ud3hkLXhLMXc1UHZFIiwidHlwIjoia2Irand0IiwiYWxnIjoiRWREU0EifQ.eyJpYXQiOjE3MjM1NjUzNzMsImF1ZCI6Imh0dHA6Ly9ob3N0LmRvY2tlci5pbnRlcm5hbDo3MDAzL29wZW5pZDR2Yy92ZXJpZnkiLCJub25jZSI6ImQyMTFlZGRjLTE2YjAtNGY1Yy1hZDZhLWU1ZjMzYzZjMjVkZCIsInNkX2hhc2giOiJzOEt1YzNWVldha2RlaWQ5WWJQMHF3RnduRld2NTFMS3g3THlmeXdjeTdFIn0.x_2dIW03plZzN3ND5OUwVXKg2JxD0Vro8_gOSe5PdWM-7dnUly4a19WR7a1j2fJ2AA4Wo3kBYl71rr-I-pDSBQ`

If I understand correctly, the latest version of OID4VP inntroduces somes non-normative examples of Authorization Response for mdoc and sd-jwt-vc. For these two formats, the credentials are no longer wrapped into another jwt with *vp* claim ? And only w3c vc-jwts are wrapped ?  

Thank you team for the help
Hoan

**Comment by severinstampler** [comment]
Hi Hoan,
Thanks for your report. 
With regards to the selective disclosures not being sent by the wallet:
The issue was recently under investigation and has been fixed today: [code](https://github.com/walt-id/waltid-identity/blame/a00220ab8e1abfc7ff9ad23b61a69b5c9c60691a/waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt#L203).
The TODO you're referring to is not directly related to this issue, but suggests a refactoring of the current implementation.
Please note, that the changes are not yet deployed on our test environments, but should be available soon.

As for the verifiable presentation wrapper objects: You're right, the OID4VP spec for sd-jwt-vc and mdoc does no longer involve wrapping the credentials in a presentation object. Instead, for the sd-jwt-vc, a key binding JWT is attached to the presented sd-jwt after the disclosures. The mdoc spec has it's own way of including a holder key binding as well.

Hope I could help, best regards
Severin
