### ISSUE TITLE
interaction between waltid-verifier-api does not work anymore with web wallet on https://wallet.walt.id/

### ISSUE THREAD

**Issue by janducaju** [walt-id/waltid-identity#774]
We have deployed the waltid-verifier-api (and waltid-issuer-api) with images from dockerhub [waltid/verifier-api - Docker Image | Docker Hub](https://hub.docker.com/r/waltid/verifier-api) and use the waltid web user wallet on [https://wallet.walt.id/](https://wallet.walt.id/)

Since Product Update #15 the interaction with the web user wallet https://wallet.walt.id/ does not work anymore. In the Chrome devtools I see the following error when posting the Offer URL in the web wallet on https://wallet.walt.id/ :
resolvePresentationRequest
{"exception":true,"status":"Internal Server Error","code":"500","message":"Invalid presentation definition reference, deserialization failed due to: Cannot read Json element because of unexpected end of the input at path: $\nJSON input: "}
<img width="959" alt="Screenshot 0 waltid wallet" src="https://github.com/user-attachments/assets/2c6e012f-afad-4f3c-909f-9682bae1bbeb">
<img width="959" alt="Screenshot waltid wallet" src="https://github.com/user-attachments/assets/22ab9f28-5ed5-4533-8625-476b827c0abb">
<img width="959" alt="Screenshot 2 waltid wallet" src="https://github.com/user-attachments/assets/b1619482-5418-44ca-b09e-d339cfd8be7d">

Additional info:
On the waltid-verifier-api container https://waltid-verifier-api.q.icts.kuleuven.be/swagger/index.html#/Credential%20Verification/post_openid4vc_verify 
I initialize OIDC presentation request: 
<img width="928" alt="Screenshot waltid-verifier-api" src="https://github.com/user-attachments/assets/c9955f9e-ff34-48af-b08c-e28d5d2d46cd">

curl -X 'POST' \
  'https://waltid-verifier-api.q.icts.kuleuven.be/openid4vc/verify' \
  -H 'accept: */*' \
  -H 'authorizeBaseUrl: openid4vp://authorize' \
  -H 'responseMode: direct_post' \
  -H 'successRedirectUri: https://myacademicid.una-europa.eu/id=$id' \
  -H 'errorRedirectUri: https://myacademicid.una-europa.eu/id=$id' \
  -H 'Content-Type: application/json' \
  -d '{
  "request_credentials": [
    {
      "format": "jwt_vc_json",
      "type": "UniversityDegreeCredential"
    }
  ]
}'

And paste the response body in the wallet https://wallet.walt.id/
openid4vp://authorize?response_type=vp_token&client_id=http%3A%2F%2Fwaltid-verifier-api.q.icts.kuleuven.be%2Fopenid4vc%2Fverify&response_mode=direct_post&state=R0zN05PR5aZE&presentation_definition_uri=http%3A%2F%2Fwaltid-verifier-api.q.icts.kuleuven.be%2Fopenid4vc%2Fpd%2FR0zN05PR5aZE&client_id_scheme=redirect_uri&client_metadata=%7B%22authorization_encrypted_response_alg%22%3A%22ECDH-ES%22%2C%22authorization_encrypted_response_enc%22%3A%22A256GCM%22%7D&nonce=8758ac8b-094f-42c8-a8b9-5c7f8734d5d0&response_uri=http%3A%2F%2Fwaltid-verifier-api.q.icts.kuleuven.be%2Fopenid4vc%2Fverify%2FR0zN05PR5aZE
I get in the devtools of the browser the error below
resolvePresentationRequest
{"exception":true,"status":"Internal Server Error","code":"500","message":"Invalid presentation definition reference, deserialization failed due to: Cannot read Json element because of unexpected end of the input at path: $\nJSON input: "}

Logs of waltid-verifier-api
Sep 26, 2024 @ 09:02:19.946	07:02:19.946046900  INFO [          D-worker-8] :     ktor.application : 200 OK: GET - /swagger/index.html in 3ms
Sep 26, 2024 @ 09:02:19.945	07:02:19.944550802 TRACE [          D-worker-8] : i.k.s.p.c.ContentNeg : Skipping because body is already converted.
Sep 26, 2024 @ 09:02:19.945	07:02:19.944873771 TRACE [          D-worker-8] : i.k.s.p.c.Compressio : Encoding body using gzip.
Sep 26, 2024 @ 09:02:19.945	07:02:19.944943652 TRACE [          D-worker-8] : i.k.s.p.s.StatusPage : No status code found for call: /swagger/index.html
Sep 26, 2024 @ 09:02:09.718	07:02:09.718371029  INFO [          D-worker-8] :     ktor.application : 200 OK: POST - /openid4vc/verify in 82ms
Sep 26, 2024 @ 09:02:09.717	07:02:09.716421711 TRACE [          D-worker-8] : i.k.s.p.s.StatusPage : No status code found for call: /openid4vc/verify
Sep 26, 2024 @ 09:02:09.716	07:02:09.716090464 TRACE [          D-worker-8] : i.k.s.p.c.ContentNeg : Skipping response body transformation from String to OutgoingContent for the POST /openid4vc/verify request because the String type is ignored. See [ContentNegotiationConfig::ignoreType].
Sep 26, 2024 @ 09:02:09.716	07:02:09.716347798 TRACE [          D-worker-8] : i.k.s.p.c.Compressio : Encoding body using gzip.
Sep 26, 2024 @ 09:02:09.671	07:02:09.670756877 DEBUG [     D-w-8+r-handler] :         Verification : Presentation definition: {"id":"61tJTSh811Q3","input_descriptors":[{"id":"UniversityDegreeCredential","format":{"jwt_vc_json":{"alg":["EdDSA"]}},"constraints":{"fields":[{"path":["$.type"],"filter":{"type":"string","pattern":"UniversityDegreeCredential"}}]}}]}
Sep 26, 2024 @ 09:02:09.651	07:02:09.651286232 TRACE [          D-worker-8] : i.k.s.p.d.DoubleRece : Storing transformed body for type class kotlinx.serialization.json.JsonObject in memory cache
Sep 26, 2024 @ 09:02:09.641	07:02:09.640960523 TRACE [          D-worker-8] : i.k.s.e.DefaultTrans : No Default Transformations found for class io.ktor.utils.io.ByteBufferChannel and expected type TypeInfo(type=class kotlinx.serialization.json.JsonObject, reifiedType=class kotlinx.serialization.json.JsonObject, kotlinType=kotlinx.serialization.json.JsonObject) for call /openid4vc/verify
Sep 26, 2024 @ 09:02:09.640	07:02:09.639409267 TRACE [          D-worker-8] : i.k.s.p.d.DoubleRece : Storing raw body in memory cache
Sep 26, 2024 @ 09:01:59.940	07:01:59.940629743  INFO [          D-worker-8] :     ktor.application : 200 OK: GET - /swagger/index.html in 2ms

**Comment by dinkar-jain** [comment]
The problem here is, that the presentation_definition_uri in the authorization request has "http://…" as the protocol, but the server redirects to "https://…". Our http client on the wallet backend, doesn't currently follow redirects, but tries to parse the empty body of the redirect response.

The best quick solution to the problem, would be to update the "baseUrl" field of the verifier API configuration, to "https://…".

**Comment by janducaju** [comment]
Thanks! Problem solved.
I feel ashamed ([Allo Allo - what-a-mistaka-to-maka](https://www.youtube.com/watch?v=b6lW1FbSHXA))
