### ISSUE TITLE
Problem with the Web Portal

### ISSUE THREAD

**Issue by InigoValdivielso** [walt-id/waltid-identity#794]
I have downloaded the latest version of the .tar and when it comes to deploying the container with docker, I enter port 7102 corresponding to the Web Portal and no credentials appear. Is it some version error or what should I do to fix it? Thank you so much.

![image](https://github.com/user-attachments/assets/e56c93d9-837b-409d-9d4e-ec61068ab772)

**Comment by dinkar-jain** [comment]
Hey @InigoValdivielso, could you please share some console screenshots or a step-by-step guide of the process you followed? This will help us easily recreate the issue. Thanks!

**Comment by InigoValdivielso** [comment]
It's already fixed thanks
