### ISSUE TITLE
Issue while trying to create cheqd DID in wallet Api

### ISSUE THREAD

**Issue by eminademburan** [walt-id/waltid-identity#809]
When I try to create a cheqd did using the "/wallet-api/wallet/{wallet}/dids/create/cheqd" endpoint, I am getting the following error:
 
{"exception":true,"status":"Bad Request","code":"400","message":"Failed to finalize the did onboarding process.\nCheqd registrar returning \"The operation failed due to an internal error. Please try again: Error: Broadcasting transaction failed with code 5 (codespace: sdk). Log: failed to deduct fees from cheqd1rnr5jrt4exl0samwj0yegv99jeskl0hsxmcz96: spendable balance 45135161199ncheq is smaller than 50000000000ncheq: insufficient funds: insufficient funds\""}

Can you help me to solve this problem?

**Comment by alegomes** [comment]
Hi @eminademburan 

I've just tried with our [managed instance](https://wallet.walt.id/swagger/index.html#/DIDs/post_wallet_api_wallet__wallet__dids_create_cheqd) and it seems to be working.

![image](https://github.com/user-attachments/assets/53cdb04d-5ac9-434f-ba45-5748d9b55fc7)

Happy holidays,
Ale
