### ISSUE TITLE
openid4vc verifiy policy "presentation-definition", why can verified success, with credentials  out of list request_credentials.

### ISSUE THREAD

**Issue by thanachot30** [walt-id/waltid-identity#842]
## Describe the bug
I am currently testing the verifier using the "presentation-definition" policy. From my understanding, the "presentation-definition" policy works by checking the VP to see if the presented credentials match exactly with the list in request_credentials. If everything matches perfectly, it passes. However, if there are any missing or additional credentials, it results in an error.

But today, I tested it, and it failed.

## To Reproduce
useing walt.id v0.9.0
1. create Presentation definition for verifier (https://verifier.portal.walt.id)
```
{
   "vp_policies": [
      "signature",
      "expired",
      "not-before",
      "presentation-definition"
   ],
   "vc_policies": [
      "signature",
      "expired",
      "not-before"
   ],
   "request_credentials": [
      {
         "format": "jwt_vc_json",
         "type": "BankId"
      },
      {
         "format": "jwt_vc_json",
         "type": "PND91Credential"
      }
   ]
}
```
for get qr
2. go to walt.id wallet (https://wallet.walt.id/login)
and present 
this is list vc for present (So, in list is not have "PND91Credential")
<img width="464" alt="vc_5" src="https://github.com/user-attachments/assets/27facfd6-35ce-4565-9dfc-99dd93ab48c1">

and send disclose

4. the result of verifier is 'success', !!!!
<img width="378" alt="vc_6" src="https://github.com/user-attachments/assets/fe0b47ca-bd71-460a-87b0-468748a78626">

why i can verifier success ?,

## Expected behavior
i Expected error verifier and throw error "missingCredentialTypes"

**Comment by cpatsonakis** [comment]
Hello @thanachot30 ,

Thanks for submitting your report.

From what I can infer from the screenshots you have provided, the wallet that you are working with
has a BankId credential, but **not** a PND91Credential, right? Please confirm so that we have the
full picture of the situation.

Thanks again and we'll come back to this issue!

**Comment by cpatsonakis** [comment]
Hello again,

A fix to the bug that you have encountered is part of #861 . Please update to the latest version once the
referenced PR has been merged to the main branch.

Thanks!
