### ISSUE TITLE
Wallet API list credentials wrong results

### ISSUE THREAD

**Issue by antoniogfs** [walt-id/waltid-identity#843]
## Describe the bug
The list credential endpoint of the Wallet API return an empty list of credentials.

## To Reproduce
1. Register an issuer in the wallet api
2. enable all the default credentials in the issuer api through the config file [credetial-issuer-metadata.conf](waltid-services/waltid-issuer-api/config/credential-issuer-metadata.conf) (uncomment line from 5 to 31).

1. call the endpoint /wallet-api/wallet/{wallet}/credentials

## Expected behavior

A list of 26 credentials

## Actual behavior

An empty list

## Additional context

I think, the issue is in method fetchCredentials from the class [IssuerUseCaseImpl](waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/issuer/IssuerUseCaseImpl.kt). This method get the credentials from the /.well-known/openid-credential-issuer, but expect to find the types of the credential from the property "types" on the root of the json object while in reality this property (but in sigular - "type") is a child of property "credential_definition". 

Not beeing able to find that property, the method ends up filtering all the credentials and gives back an empty list.

**Comment by severinstampler** [comment]
The credentialals endpoint you mention is meant to list the credentials, that have been issued to your wallet. Not yhe credentials offered by any issuer. If you created a new wallet, the empty list is the expected behaviour.

**Comment by severinstampler** [comment]
the buggy endpoint is: /wallet-api/wallet/{wallet}/issuers/{issuer}/credentials

Working on a solution...

**Comment by antoniogfs** [comment]
Sorry, but I do not think that this is correct. 

The endpoint /wallet-api/wallet/{wallet}/issuers/{issuer}/credentials, which is exactly the endpoint I referenced in the issue, call in the background the endpoint /.well-known/openid-credential-issuer from the issuer. This last endpoint, list all the available credential offered (not issued) by the issuer to anyone and therefore also to this specific wallet.

So the possibilities are two: either the implementation is incorrect according to the intention or the implementation is correct but then the intention is wrong.

**Comment by severinstampler** [comment]
A fix has been implemented with this pull request: https://github.com/walt-id/waltid-identity/pull/863
Once, it's merged it should be fixed.

**Comment by antoniogfs** [comment]
Thank you
