### ISSUE TITLE
Event logs GET api not responding as expected

### ISSUE THREAD

**Issue by surabhi-dudhediya** [walt-id/waltid-identity#858]
In the Wallet APIs, there is a GET api of event logs `/wallet-api/wallet/{wallet}/eventlog` which retrieves the event logs for currently signed in account wallet. This api has only one mandate query parameter as wallet id. Even after passing the correct wallet id to the api, the api is throwing below error
`{"exception":true,"status":"Bad Request","code":"400","message":"No such configuration registered: \"id.walt.webwallet.config.TrustConfig\"!"}`. Kindly provide me the solution for the same.

**Comment by mikeplotean** [comment]
hi, sounds like you're using an older version of the stack<br>could you please try with a more recent one, e.g. [v0.9.0](https://github.com/walt-id/waltid-identity/releases/tag/v0.9.0)?

**Comment by surabhi-dudhediya** [comment]
hi @mikeplotean, I am using the latest version only. I am running the application on docker desktop, and having all the containers running locally

**Comment by mikeplotean** [comment]
confirming I could reproduce it<br>will try to squeeze a fix in the next release
